let characterData = [
    {
        "character": "Ryu", "platform": "Steam",
        "totalMatches": 196, "overallWinrate": 0.4388,
        "matchups": [
            { "vs": "Ryu", "matches": 15, "winrate": 0.2667 },
            { "vs": "Ken", "matches": 24, "winrate": 0.5417 },
            { "vs": "Cammy", "matches": 8, "winrate": 0.25 },
            { "vs": "M Bison", "matches": 10, "winrate": 0.2 },
            { "vs": "Karin", "matches": 2, "winrate": 1 },
            { "vs": "R Mika", "matches": 2, "winrate": 1 },
            { "vs": "Zangief", "matches": 11, "winrate": 0.3636 },
            { "vs": "Dhalsim", "matches": 2, "winrate": 0 },
            { "vs": "Rashid", "matches": 8, "winrate": 0.625 },
            { "vs": "Laura", "matches": 6, "winrate": 0.3333 },
            { "vs": "FANG", "matches": 2, "winrate": 0.5 },
            { "vs": "Necalli", "matches": 3, "winrate": 0.3333 },
            { "vs": "Alex", "matches": 3, "winrate": 0.3333 },
            { "vs": "Guile", "matches": 5, "winrate": 0.4 },
            { "vs": "Balrog", "matches": 2, "winrate": 1 },
            { "vs": "Juri", "matches": 5, "winrate": 0.6 },
            { "vs": "Urien", "matches": 2, "winrate": 0 },
            { "vs": "Akuma", "matches": 22, "winrate": 0.4091 },
            { "vs": "Kolin", "matches": 8, "winrate": 0 },
            { "vs": "Ed", "matches": 10, "winrate": 0.7 },
            { "vs": "Abigail", "matches": 5, "winrate": 0.2 },
            { "vs": "Zeku", "matches": 3, "winrate": 0.6667 },
            { "vs": "Sakura", "matches": 7, "winrate": 0.7143 },
            { "vs": "Blanka", "matches": 2, "winrate": 1 },
            { "vs": "Cody", "matches": 11, "winrate": 0.3636 },
            { "vs": "G", "matches": 2, "winrate": 0.5 },
            { "vs": "Sagat", "matches": 3, "winrate": 0.6667 },
            { "vs": "Kage", "matches": 6, "winrate": 0.6667 },
            { "vs": "Lucia", "matches": 4, "winrate": 0 },
            { "vs": "Dan", "matches": 3, "winrate": 1 },
        ]
    },
    {
        "character": "Cammy", "platform": "Steam",
        "totalMatches": 10, "overallWinrate": 0.3,
        "matchups": [
            { "vs": "Juri", "matches": 2, "winrate": 0 },
            { "vs": "Akuma", "matches": 8, "winrate": 0.375 },
        ]
    },
    {
        "character": "Birdie", "platform": "Steam",
        "totalMatches": 1146, "overallWinrate": 0.4895,
        "matchups": [
            { "vs": "Ryu", "matches": 165, "winrate": 0.533 },
            { "vs": "Ken", "matches": 91, "winrate": 0.5385 },
            { "vs": "Chun Li", "matches": 23, "winrate": 0.8261 },
            { "vs": "Cammy", "matches": 29, "winrate": 0.5172 },
            { "vs": "Nash", "matches": 21, "winrate": 0.619 },
            { "vs": "M Bison", "matches": 39, "winrate": 0.2308 },
            { "vs": "Vega", "matches": 11, "winrate": 0.2727 },
            { "vs": "Birdie", "matches": 10, "winrate": 0.5 },
            { "vs": "Karin", "matches": 32, "winrate": 0.4063 },
            { "vs": "R Mika", "matches": 11, "winrate": 0.5455 },
            { "vs": "Zangief", "matches": 53, "winrate": 0.3962 },
            { "vs": "Dhalsim", "matches": 5, "winrate": 1 },
            { "vs": "Rashid", "matches": 18, "winrate": 0.3889 },
            { "vs": "Laura", "matches": 46, "winrate": 0.3261 },
            { "vs": "FANG", "matches": 13, "winrate": 0.3846 },
            { "vs": "Necalli", "matches": 7, "winrate": 0.8571 },
            { "vs": "Alex", "matches": 28, "winrate": 0.5714 },
            { "vs": "Guile", "matches": 57, "winrate": 0.3509 },
            { "vs": "Ibuki", "matches": 15, "winrate": 0.4667 },
            { "vs": "Balrog", "matches": 26, "winrate": 0.6154 },
            { "vs": "Juri", "matches": 18, "winrate": 0.5 },
            { "vs": "Urien", "matches": 10, "winrate": 0.5 },
            { "vs": "Akuma", "matches": 56, "winrate": 0.4107 },
            { "vs": "Kolin", "matches": 17, "winrate": 0.5294 },
            { "vs": "Ed", "matches": 8, "winrate": 0.5 },
            { "vs": "Abigail", "matches": 21, "winrate": 0.3333 },
            { "vs": "Menat", "matches": 11, "winrate": 0.3636 },
            { "vs": "Zeku", "matches": 11, "winrate": 0.6364 },
            { "vs": "Sakura", "matches": 22, "winrate": 0.5 },
            { "vs": "Blanka", "matches": 2, "winrate": 0 },
            { "vs": "Falke", "matches": 11, "winrate": 0.4545 },
            { "vs": "Cody", "matches": 13, "winrate": 0.5385 },
            { "vs": "G", "matches": 5, "winrate": 1 },
            { "vs": "Sagat", "matches": 21, "winrate": 0.6667 },
            { "vs": "Kage", "matches": 58, "winrate": 0.5862 },
            { "vs": "Poision", "matches": 6, "winrate": 0.6667 },
            { "vs": "E. Honda", "matches": 16, "winrate": 0.3125 },
            { "vs": "Lucia", "matches": 14, "winrate": 0.2857 },
            { "vs": "Gill", "matches": 11, "winrate": 0.4545 },
            { "vs": "Seth", "matches": 13, "winrate": 0.6154 },
            { "vs": "Dan", "matches": 18, "winrate": 0.6667 },
            { "vs": "Rose", "matches": 5, "winrate": 0.6 },
            { "vs": "Oro", "matches": 3, "winrate": 0.3333 },
            { "vs": "Akira", "matches": 28, "winrate": 0.4286 },
            { "vs": "Luke", "matches": 48, "winrate": 0.5208 },
        ]
    },
    {
        "character": "Guile", "platform": "Steam",
        "totalMatches": 32, "overallWinrate": 0.5313,
        "matchups": [
            { "vs": "Ryu", "matches": 5, "winrate": 0.2 },
            { "vs": "Ken", "matches": 6, "winrate": 0.6667 },
            { "vs": "Cammy", "matches": 3, "winrate": 0.6667 },
            { "vs": "Nash", "matches": 2, "winrate": 0 },
            { "vs": "Birdie", "matches": 3, "winrate": 0.6667 },
            { "vs": "Laura", "matches": 1, "winrate": 0 },
            { "vs": "Necalli", "matches": 1, "winrate": 0 },
            { "vs": "Guile", "matches": 2, "winrate": 0 },
            { "vs": "Akuma", "matches": 5, "winrate": 0.8 },
            { "vs": "Kolin", "matches": 2, "winrate": 1 },
            { "vs": "Falke", "matches": 2, "winrate": 1 },
        ]
    },
    {
        "character": "Balrog", "platform": "Steam",
        "totalMatches": 78, "overallWinrate": 0.5,
        "matchups": [
            { "vs": "Ryu", "matches": 8, "winrate": 0.75 },
            { "vs": "Ken", "matches": 5, "winrate": 0.4 },
            { "vs": "Cammy", "matches": 8, "winrate": 0.75 },
            { "vs": "Vega", "matches": 2, "winrate": 0 },
            { "vs": "Birdie", "matches": 2, "winrate": 1 },
            { "vs": "Karin", "matches": 2, "winrate": 0 },
            { "vs": "Zangief", "matches": 9, "winrate": 0.2222 },
            { "vs": "Dhalsim", "matches": 4, "winrate": 1 },
            { "vs": "Rashid", "matches": 2, "winrate": 0 },
            { "vs": "FANG", "matches": 2, "winrate": 1 },
            { "vs": "Necalli", "matches": 2, "winrate": 0 },
            { "vs": "Alex", "matches": 2, "winrate": 0 },
            { "vs": "Urien", "matches": 1, "winrate": 0 },
            { "vs": "Ed", "matches": 3, "winrate": 0.6667 },
            { "vs": "Abigail", "matches": 1, "winrate": 1 },
            { "vs": "Sakura", "matches": 5, "winrate": 0.2 },
            { "vs": "Cody", "matches": 2, "winrate": 0 },
            { "vs": "Sagat", "matches": 4, "winrate": 1 },
            { "vs": "Poision", "matches": 9, "winrate": 0.5556 },
            { "vs": "E. Honda", "matches": 1, "winrate": 0 },
            { "vs": "Lucia", "matches": 4, "winrate": 0.5 },
        ]
    },
    {
        "character": "Kolin", "platform": "Steam",
        "totalMatches": 106, "overallWinrate": 0.4717,
        "matchups": [
            { "vs": "Ryu", "matches": 16, "winrate": 0.6857 },
            { "vs": "Ken", "matches": 6, "winrate": 0.3333 },
            { "vs": "Chun Li", "matches": 4, "winrate": 0.5 },
            { "vs": "Cammy", "matches": 12, "winrate": 0.5 },
            { "vs": "Vega", "matches": 2, "winrate": 1 },
            { "vs": "Birdie", "matches": 5, "winrate": 0.2 },
            { "vs": "Karin", "matches": 9, "winrate": 0.5556 },
            { "vs": "R Mika", "matches": 3, "winrate": 0.6667 },
            { "vs": "Zangief", "matches": 6, "winrate": 0.3333 },
            { "vs": "Laura", "matches": 2, "winrate": 0.5 },
            { "vs": "Necalli", "matches": 6, "winrate": 0.5 },
            { "vs": "Balrog", "matches": 3, "winrate": 0.3333 },
            { "vs": "Juri", "matches": 7, "winrate": 0.1429 },
            { "vs": "Urien", "matches": 2, "winrate": 0 },
            { "vs": "Akuma", "matches": 9, "winrate": 0.1111 },
            { "vs": "Menat", "matches": 5, "winrate": 0.8 },
            { "vs": "Zeku", "matches": 9, "winrate": 0.6667 },
        ]
    },
    {
        "character": "Sakura", "platform": "Steam",
        "totalMatches": 7, "overallWinrate": 0.2857,
        "matchups": [
            { "vs": "Ken", "matches": 2, "winrate": 1 },
            { "vs": "M Bison", "matches": 2, "winrate": 0 },
            { "vs": "FANG", "matches": 1, "winrate": 0 },
            { "vs": "Akuma", "matches": 2, "winrate": 0 },
        ]
    },
    {
        "character": "Cody", "platform": "Steam",
        "totalMatches": 182, "overallWinrate": 0.5714,
        "matchups": [
            { "vs": "Ryu", "matches": 45, "winrate": 0.6889 },
            { "vs": "Ken", "matches": 9, "winrate": 0.4444 },
            { "vs": "Chun Li", "matches": 2, "winrate": 1 },
            { "vs": "Cammy", "matches": 14, "winrate": 0.6429 },
            { "vs": "Nash", "matches": 5, "winrate": 0.6 },
            { "vs": "M Bison", "matches": 5, "winrate": 0.2 },
            { "vs": "Birdie", "matches": 4, "winrate": 0 },
            { "vs": "Karin", "matches": 4, "winrate": 0.5 },
            { "vs": "R Mika", "matches": 2, "winrate": 1 },
            { "vs": "Zangief", "matches": 6, "winrate": 0.8333 },
            { "vs": "Rashid", "matches": 2, "winrate": 1 },
            { "vs": "Laura", "matches": 4, "winrate": 0 },
            { "vs": "FANG", "matches": 1, "winrate": 1 },
            { "vs": "Alex", "matches": 4, "winrate": 0 },
            { "vs": "Guile", "matches": 14, "winrate": 0.7143 },
            { "vs": "Ibuki", "matches": 3, "winrate": 0.6667 },
            { "vs": "Balrog", "matches": 3, "winrate": 0.3333 },
            { "vs": "Juri", "matches": 7, "winrate": 0.2857 },
            { "vs": "Akuma", "matches": 14, "winrate": 0.7143 },
            { "vs": "Kolin", "matches": 5, "winrate": 0.2 },
            { "vs": "Ed", "matches": 2, "winrate": 0 },
            { "vs": "Abigail", "matches": 2, "winrate": 0 },
            { "vs": "Menat", "matches": 2, "winrate": 1 },
            { "vs": "Zeku", "matches": 2, "winrate": 0 },
            { "vs": "Sakura", "matches": 8, "winrate": 0.625 },
            { "vs": "Falke", "matches": 2, "winrate": 0.5 },
            { "vs": "Cody", "matches": 8, "winrate": 0.75 },
            { "vs": "Sagat", "matches": 3, "winrate": 0.3333 },
        ]
    },
    {
        "character": "Ryu", "platform": "PS4",
        "totalMatches": 277, "overallWinrate": 0.509,
        "matchups": [
            { "vs": "Ryu", "matches": 66, "winrate": 0.5 },
            { "vs": "Ken", "matches": 34, "winrate": 0.5588 },
            { "vs": "Chun Li", "matches": 12, "winrate": 0.5833 },
            { "vs": "Cammy", "matches": 26, "winrate": 0.6538 },
            { "vs": "Nash", "matches": 15, "winrate": 0.4 },
            { "vs": "M Bison", "matches": 6, "winrate": 0.1667 },
            { "vs": "Vega", "matches": 14, "winrate": 0.5 },
            { "vs": "Birdie", "matches": 9, "winrate": 0.6667 },
            { "vs": "Karin", "matches": 25, "winrate": 0.4 },
            { "vs": "R Mika", "matches": 12, "winrate": 0.6667 },
            { "vs": "Zangief", "matches": 13, "winrate": 0.4615 },
            { "vs": "Dhalsim", "matches": 3, "winrate": 1 },
            { "vs": "Rashid", "matches": 11, "winrate": 0.3636 },
            { "vs": "Laura", "matches": 11, "winrate": 0.5455 },
            { "vs": "FANG", "matches": 1, "winrate": 1 },
            { "vs": "Necalli", "matches": 9, "winrate": 0.1111 },
            { "vs": "Alex", "matches": 3, "winrate": 0.6667 },
            { "vs": "Ibuki", "matches": 3, "winrate": 0.6667 },
            { "vs": "Balrog", "matches": 2, "winrate": 0 },
            { "vs": "Akuma", "matches": 2, "winrate": 1 },
        ]
    },
    {
        "character": "Ken", "platform": "PS4",
        "totalMatches": 35, "overallWinrate": 0.2857,
        "matchups": [
            { "vs": "Ryu", "matches": 14, "winrate": 0.1429 },
            { "vs": "Ken", "matches": 2, "winrate": 0 },
            { "vs": "Nash", "matches": 3, "winrate": 0.3333 },
            { "vs": "M Bison", "matches": 2, "winrate": 0 },
            { "vs": "Vega", "matches": 2, "winrate": 0 },
            { "vs": "Rashid", "matches": 2, "winrate": 1 },
            { "vs": "Laura", "matches": 5, "winrate": 0.4 },
            { "vs": "FANG", "matches": 2, "winrate": 1 },
            { "vs": "Necalli", "matches": 3, "winrate": 0.3333 },
        ]
    },
    {
        "character": "Chun Li", "platform": "PS4",
        "totalMatches": 13, "overallWinrate": 0.2308,
        "matchups": [
            { "vs": "Ryu", "matches": 5, "winrate": 0.2 },
            { "vs": "Chun Li", "matches": 1, "winrate": 0 },
            { "vs": "Cammy", "matches": 2, "winrate": 1 },
            { "vs": "Nash", "matches": 1, "winrate": 0 },
            { "vs": "Necalli", "matches": 4, "winrate": 0 },
        ]
    },
    {
        "character": "M Bison", "platform": "PS4",
        "totalMatches": 48, "overallWinrate": 0.3958,
        "matchups": [
            { "vs": "Ryu", "matches": 10, "winrate": 0.7 },
            { "vs": "Ken", "matches": 2, "winrate": 0 },
            { "vs": "Chun Li", "matches": 2, "winrate": 0 },
            { "vs": "Cammy", "matches": 6, "winrate": 0.3333 },
            { "vs": "Nash", "matches": 7, "winrate": 0.4286 },
            { "vs": "Karin", "matches": 8, "winrate": 0.25 },
            { "vs": "Zangief", "matches": 2, "winrate": 0 },
            { "vs": "Dhalsim", "matches": 1, "winrate": 1 },
            { "vs": "Laura", "matches": 2, "winrate": 0 },
            { "vs": "FANG", "matches": 2, "winrate": 1 },
            { "vs": "Necalli", "matches": 1, "winrate": 1 },
            { "vs": "Alex", "matches": 5, "winrate": 0.2 },
        ]
    },
    {
        "character": "Birdie", "platform": "PS4",
        "totalMatches": 125, "overallWinrate": 0.384,
        "matchups": [
            { "vs": "Ryu", "matches": 25, "winrate": 0.48 },
            { "vs": "Ken", "matches": 14, "winrate": 0.5 },
            { "vs": "Chun Li", "matches": 5, "winrate": 0.8 },
            { "vs": "Cammy", "matches": 10, "winrate": 0.3 },
            { "vs": "Nash", "matches": 8, "winrate": 0.25 },
            { "vs": "Birdie", "matches": 5, "winrate": 0.2 },
            { "vs": "Karin", "matches": 12, "winrate": 0.4167 },
            { "vs": "R Mika", "matches": 6, "winrate": 0.1667 },
            { "vs": "Zangief", "matches": 10, "winrate": 0.3 },
            { "vs": "Rashid", "matches": 5, "winrate": 0.2 },
            { "vs": "FANG", "matches": 2, "winrate": 0 },
            { "vs": "Necalli", "matches": 13, "winrate": 0.3846 },
            { "vs": "Alex", "matches": 3, "winrate": 0 },
            { "vs": "Guile", "matches": 7, "winrate": 0.5714 },
        ]
    },
    {
        "character": "Alex", "platform": "PS4",
        "totalMatches": 25, "overallWinrate": 0.16,
        "matchups": [
            { "vs": "Ryu", "matches": 7, "winrate": 0.1429 },
            { "vs": "Ken", "matches": 2, "winrate": 0 },
            { "vs": "Cammy", "matches": 2, "winrate": 0 },
            { "vs": "Nash", "matches": 1, "winrate": 1 },
            { "vs": "M Bison", "matches": 3, "winrate": 0.3333 },
            { "vs": "Vega", "matches": 3, "winrate": 0.3333 },
            { "vs": "R Mika", "matches": 4, "winrate": 0 },
            { "vs": "Zangief", "matches": 2, "winrate": 0 },
            { "vs": "Necalli", "matches": 1, "winrate": 0 },
        ]
    },
    {
        "character": "Guile", "platform": "PS4",
        "totalMatches": 44, "overallWinrate": 0.2045,
        "matchups": [
            { "vs": "Ryu", "matches": 10, "winrate": 0.1 },
            { "vs": "Ken", "matches": 6, "winrate": 0.5 },
            { "vs": "Chun Li", "matches": 2, "winrate": 0 },
            { "vs": "Cammy", "matches": 1, "winrate": 0 },
            { "vs": "Nash", "matches": 4, "winrate": 0 },
            { "vs": "Karin", "matches": 4, "winrate": 0 },
            { "vs": "R Mika", "matches": 4, "winrate": 0.5 },
            { "vs": "Dhalsim", "matches": 4, "winrate": 0.5 },
            { "vs": "FANG", "matches": 2, "winrate": 0 },
            { "vs": "Alex", "matches": 3, "winrate": 0.3333 },
            { "vs": "Guile", "matches": 4, "winrate": 0 },
        ]
    },
];
