hugo --contentDir collections_root --config collections.toml,local.toml --destination C:/repos/collections
hugo --contentDir collections/lyrics --config collections.toml,local.toml,collections/lyrics/lyrics.toml --destination C:/repos/collections/lyrics
hugo --contentDir collections/quotes --config collections.toml,local.toml,collections/quotes/quotes.toml --destination C:/repos/collections/quotes
hugo --contentDir collections/comics --config collections.toml,local.toml,collections/comics/comics.toml --destination C:/repos/collections/comics
hugo --contentDir collections/albums --config collections.toml,local.toml,collections/albums/albums.toml --destination C:/repos/collections/albums
hugo --contentDir collections/stackexchange --config collections.toml,local.toml,collections/stackexchange/stackexchange.toml --destination C:/repos/collections/stackexchange
hugo --contentDir collections/webcomics --config collections.toml,local.toml,collections/webcomics/webcomics.toml --destination C:/repos/collections/webcomics
hugo --contentDir collections/quora --config collections.toml,local.toml,collections/quora/quora.toml --destination C:/repos/collections/quora
hugo --contentDir collections/sketchbook --config collections.toml,local.toml,collections/sketchbook/sketchbook.toml --destination C:/repos/collections/sketchbook
hugo --contentDir collections/threads --config collections.toml,local.toml,collections/threads/threads.toml --destination C:/repos/collections/threads
hugo --contentDir collections/surveys --config collections.toml,local.toml,collections/surveys/surveys.toml --destination C:/repos/collections/surveys
hugo --contentDir collections/jokes --config collections.toml,local.toml,collections/jokes/jokes.toml --destination C:/repos/collections/jokes
hugo --contentDir collections/miiverse --config collections.toml,local.toml,collections/miiverse/miiverse.toml --destination C:/repos/collections/miiverse
hugo --contentDir collections/quiznights --config collections.toml,local.toml,collections/quiznights/quiznights.toml --destination C:/repos/collections/quiznights
hugo --contentDir collections/fiction --config collections.toml,local.toml,collections/fiction/fiction.toml --destination C:/repos/collections/fiction
