hugo --contentDir collections_root --config collections.toml --destination /var/www/collections/ 
hugo --contentDir collections/lyrics --config collections.toml,collections/lyrics/lyrics.toml --destination /var/www/collections/lyrics
hugo --contentDir collections/quotes --config collections.toml,collections/quotes/quotes.toml --destination /var/www/collections/quotes
hugo --contentDir collections/comics --config collections.toml,collections/comics/comics.toml --destination /var/www/collections/comics
hugo --contentDir collections/albums --config collections.toml,collections/albums/albums.toml --destination /var/www/collections/albums
hugo --contentDir collections/stackexchange --config collections.toml,collections/stackexchange/stackexchange.toml --destination /var/www/collections/stackexchange
hugo --contentDir collections/webcomics --config collections.toml,collections/webcomics/webcomics.toml --destination /var/www/collections/webcomics
hugo --contentDir collections/quora --config collections.toml,collections/quora/quora.toml --destination /var/www/collections/quora
hugo --contentDir collections/sketchbook --config collections.toml,collections/sketchbook/sketchbook.toml --destination /var/www/collections/sketchbook
hugo --contentDir collections/threads --config collections.toml,collections/threads/threads.toml --destination /var/www/collections/threads
hugo --contentDir collections/surveys --config collections.toml,collections/surveys/surveys.toml --destination /var/www/collections/surveys
hugo --contentDir collections/jokes --config collections.toml,collections/jokes/jokes.toml --destination /var/www/collections/jokes