baseURL = "https://roytang.net/"
languageCode = "en-us"
title = "roytang.net"
theme = "exhale"

# Pagination
paginate = 50
paginatePath = "p"
relativeURLs = true

ignoreErrors = ["error-output-taxonomy"]

rssLimit = 50
enableGitInfo = true
canonifyURLs = true

[mediaTypes]
  [mediaTypes."application/ld+json"]
    suffixes = ["json"]
  [mediaTypes."text/markdown"]
    suffixes = ["md"]

[outputFormats]
  [outputFormats.ActivityPub]
    baseName = "activity"
    isPlainText = true
    mediaType = "application/ld+json"
  [outputFormats.jsonfeed]
    baseName = "feed"
    isPlainText = true
    mediaType = "application/json"     
  [outputFormats.hfeed]
    baseName = "hfeed"
    mediaType = "text/html"    
  [outputFormats.mdlist]
    baseName = "list"
    mediaType = "text/markdown"    
  [outputFormats.readme]
    baseName = "README"
    mediaType = "text/markdown"    

[outputs]
  page = ["HTML"]

[taxonomies]
    quote_tag = "quotes/tags"
    comic_tag = "comics/tags"


[author]
    name = "Roy Tang"
    email = "hello@roytang.net"
    url = "https://roytang.net"

[permalinks]
    post = "/:year/:month/:slug/"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    rootPath = "collections/"
    # staticRoot = "https://roytang.net/media/"
    staticRoot = "http://localhost/repos/blog/"
    homeShowRecentItems = false

    # You can use markdown here.
    brand = "Roy Tang"
    topimage = "![Wearing dice on my head since 2008](/img/profile.jpg \"Wearing dice on my head since 2008\")"
    topline = "Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart."
    featuredImage = "https://roytang.net/img/profile.jpg"
    description = "Roy Tang's blog. Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart. Randomly amazed."
    footline = ""
    webmention_username = 'roytang.net'
    search_action = 'https://roytang.net/search/'
    sourceFileBase = 'https://github.com/roytang/blog/tree/master/content/'
    

    # Select a syntax highight for highlight.js
    # Check the static/css/highlight directory for options.
    # Leave unset to fall back to default hugo highlighter instead of highlight.js
    highlight = "default"


[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[markup.goldmark.renderer]
    unsafe= true
