baseURL = "https://roytang.net/"
languageCode = "en-us"
title = "roytang.net"
theme = "collections"
staticDir = "collections_root"

relativeURLs = true

ignoreErrors = ["error-output-taxonomy"]

rssLimit = 50
enableGitInfo = true
canonifyURLs = true

[pagination]
  pagerSize = 50

[outputFormats]
  [outputFormats.data]
    baseName = "data"
    mediaType = "application/json"    
  [outputFormats.embed]
    baseName = "embed"
    mediaType = "application/json"    
  [outputFormats.attachmentsjson]
    baseName = "attachments"
    mediaType = "application/json"    

[outputs]
  page = ["HTML", "embed", "attachmentsjson"]
  home = ["HTML", "data"]

[taxonomies]
    tags = "tags"
    locations = "locations"


[author]
    name = "Roy Tang"
    email = "hello@roytang.net"
    url = "https://roytang.net"

[permalinks]
    "notes" = "/:filename/"
    "events" = "/:filename/"
    "lineitems" = "/:filename/"
    "comics" = "/:filename/"
    "albums" = "/:filename/"
    "sketches" = "/:filename/"
    "cards" = "/:filename/"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    collections = true
    collections_root = true
    home_template = "home"
    locations = false
    rootPath = "collections/"
    mainRoot = "https://roytang.net/"
    staticRoot = "https://roytang.net/media/"
    # staticRoot = "http://localhost/repos/blog/"
    jsincludes = ["https://code.jquery.com/jquery-3.7.1.min.js", "https://roytang.net/media/static/js/jquery.photobox.js", "https://roytang.net/media/static/js/exhale.js"]
    cssincludespost = []
    thumbnailsize = "300x"
    autoinlinephotos = true

    list_class = ""
    homeShowRecentItems = false
    
    # You can use markdown here.
    brand = "Roy Tang"
    topimage = "![Wearing dice on my head since 2008](/img/profile.jpg \"Wearing dice on my head since 2008\")"
    topline = "Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart."
    featuredImage = "https://roytang.net/static/img/profile.jpg"
    description = "Roy Tang's blog. Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart. Randomly amazed."
    footline = ""
    webmention_username = 'roytang.net'
    search_action = 'https://roytang.net/search/'
    sourceFileBase = 'https://github.com/roytang/blog/tree/master/content/'
    

    # Select a syntax highight for highlight.js
    # Check the static/css/highlight directory for options.
    # Leave unset to fall back to default hugo highlighter instead of highlight.js
    highlight = "default"

    fediverse = "@roytang@indieweb.social"
    blogroll_url = "/blogroll/opml/"
    manifest_url = "/static/manifest.webmanifest"

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

[markup.goldmark.renderer]
    unsafe= true
