[params]
    rootPath = "collections/"
    staticRoot = "http://localhost/repos/blog/static/"
    mainRoot = "http://localhost:8000/"
    jsincludes = ["https://code.jquery.com/jquery-3.7.1.min.js", "http://localhost/blog/static/js/jquery.photobox.js", "http://localhost/blog/static/js/exhale.js"]
